name: Build and Test
on:
  push:
jobs:
  test-project:
    strategy:
      matrix:
        build_type: [Debug, Release]
        compiler: [gcc, clang]
    name: Test Dalotia
    runs-on: ubuntu-latest
    steps:
    - name: install valgrind
      run: sudo apt-get install valgrind
    - name: Checkout
      uses: actions/checkout@v4.2.0

    - name: Configure and Build Project
      uses: threeal/cmake-action@v1.3.0
      with:
        run-build: true
        build-args: --config ${{ matrix.build_type }}
        cxx-compiler: ${{ matrix.compiler }}
        build-dir: build-${{ matrix.compiler }}-${{ matrix.build_type }}

    - name: Test Project
      uses: threeal/ctest-action@v1.1.0
      with:
        # build-config: ${{ matrix.build_type }}
        test-dir: build-${{ matrix.compiler }}-${{ matrix.build_type }}
        args: --output-on-failure -T memcheck